<template>
  <!-- Finalization/Success Page -->
  <div class="finalization-container" style="background: var(--bs-secondary-bg-subtle);">
    <section class="position-relative py-4 py-xl-5">
      <div class="container mt-0">
        <div class="row d-flex justify-content-center">
          <div class="col-md-6 col-xl-4 ms-10" style="background: var(--bs-card-cap-bg); border-color: var(--bs-primary);">
            <div class="card w-75 ms-4 ps-0 mt-6 mb-5" 
                 style="background: var(--bs-secondary); border-radius: 57px; border-color: var(--bs-primary);">
              <div class="card-body d-flex flex-column align-items-center ms-0 mt-4 pt-0" 
                   style="background: var(--bs-secondary); border-radius: 37px;">
                
                <div class="col-md-8 col-xl-6 text-center ps-0 pe-0 mx-auto">
                  <h2 style="color: var(--bs-black); font-family: Amethysta, serif;">
                    Pedido Enviado!
                  </h2>
                  <p class="ps-6 pe-4" style="color: var(--bs-black); font-family: Amethysta, serif;">
                    Faça o pix para o QR Code abaixo com o valor de {{ formatPrice(total) }}.
                  </p>
                  
                  <!-- QR Code Placeholder -->
                  <div class="qr-code-placeholder my-4">
                    <img v-if="qrCode" :src="qrCode" alt="QR Code PIX" width="250" height="230">
                    <div v-else class="qr-placeholder" style="width: 250px; height: 230px; background: #f0d9d1; margin: 0 auto; display: flex; align-items: center; justify-content: center; border-radius: 10px;">
                      <i class="fas fa-qrcode fa-5x" style="color: #fbaa70;"></i>
                    </div>
                  </div>
                </div>
                
                <p class="ps-6 pe-4" style="color: var(--bs-black); margin-top: 8px; font-family: Amethysta, serif; font-size: 18px;">
                  Envie o comprovante para nós por WhatsApp (61) 9xxxx-xxxx.
                  Você pode acompanhar o status do pedido no seu perfil!
                </p>
                
                <div class="bg-success my-4 bs-icon-xl bs-icon-circle bs-icon-primary bs-icon" 
                     style="background: var(--bs-warning); border-color: var(--bs-success); color: var(--bs-primary);">
                  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" 
                       viewBox="0 0 16 16" class="bi bi-check">
                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"></path>
                  </svg>
                </div>
                
                <router-link to="/" style="font-family: Amethysta, serif;">
                  Voltar para página inicial →
                </router-link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()

const total = ref(0)
const qrCode = ref('')

const formatPrice = (value) => {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL'
  }).format(value)
}

onMounted(() => {
  // Get total from route params or localStorage
  total.value = route.params.total || localStorage.getItem('pedido_total') || 0
  // QR code would be generated by backend
  qrCode.value = route.params.qrCode || ''
})
</script>

<style scoped>
.finalization-container {
  min-height: 100vh;
  padding: 2rem 0;
}

.bs-icon-xl {
  width: 5rem;
  height: 5rem;
  display: flex;
  align-items: center;
  justify-content: center;
}

.bs-icon-circle {
  border-radius: 50%;
}

.bs-icon svg {
  width: 3rem;
  height: 3rem;
}

a {
  color: var(--bs-success);
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}
</style>
